name: audio_guide
description: Player for published audio guides.
publish_to: "none"
version: 0.4.3+26

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  just_audio: ^0.9.42
  path_provider: ^2.1.5
  speech_to_text: ^7.0.0
  yandex_maps_mapkit_lite: ^4.42.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  package_info_plus: ^8.1.2
  open_filex: ^4.6.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/content/pack.json
