server {
    listen 80;
    server_name 161.104.53.72;

    client_max_body_size 32m;

    location /media/ {
        alias /opt/audio_guide/content/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
